### ISSUE TITLE
[Bug] Stop button release window

### ISSUE THREAD

**Issue by Erbengi** [jirutka/hass-smarwi#17]
Stop button while window is opening/closing in the UI causes the window to be released (fix is off) instead of stopping movement. If the window does not move, the stop button does nothing.

https://github.com/user-attachments/assets/d8e422c9-2af8-4276-b5b6-edda050e91e9

**Comment by jirutka** [comment]
This is actually a bug in the Smarwi – the stop command stops the movement **and** releases the ridge. The Smarwi’s web UI does the same thing. I have to admit that I’m surprised by this, because I assumed that the stop command only releases the ridge when the device is not moving, and hadn’t noticed it until now. I’m gonna workaround it.
